name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-and-test:
    name: Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Install Linux system dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libfontconfig1-dev libx11-dev libxkbcommon-dev libx11-xcb-dev libwayland-dev libasound2-dev pkg-config


      - name: Check code formatting
        run: cargo fmt --check

      - name: Run Clippy linter
        run: cargo clippy --all-targets -- -D warnings

      - name: Run all tests (Unit, Integration, and Proptest)
        run: cargo test --all-targets --verbose
